[programs.localnet]
deposit_withdraw = "CNx5eYLkfcwRTASB8LJWKrDHHeguLi2d7Mb9ebBFMsPS"
[programs.devnet]
deposit_withdraw = "CNx5eYLkfcwRTASB8LJWKrDHHeguLi2d7Mb9ebBFMsPS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
