[programs.localnet]
deposit_withdraw = "FX1PEUJGHbKZAqcpr2wT25kBeLVhHNCT4p9SfSvKgQcc"
[programs.devnet]
deposit_withdraw = "FX1PEUJGHbKZAqcpr2wT25kBeLVhHNCT4p9SfSvKgQcc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ajackti/.config/solana/id.json"
# wallet = "/Users/ajackti/.config/solana/id2.json"


[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-mocha -p ./tsconfig.json -t 1000000 scripts/init.ts"
deposit = "ts-mocha -p ./tsconfig.json -t 1000000 scripts/deposit.ts"
withdraw = "ts-mocha -p ./tsconfig.json -t 1000000 scripts/withdraw.ts"
balance = "ts-mocha -p ./tsconfig.json -t 1000000 scripts/balance.ts"
